name: No Plans to Merge

on:
  pull_request:
    types:
      - closed

jobs:
  no-plans-to-merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == false

    steps:
      # - name: Output Context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"

      - name: Create a comment on PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'No plans to merge üëç'
            })

  apply-pint-fixes:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
    - name: Checkout Code
      uses: actions/checkout@v6.0.0
      with:
        ref: ${{ github.head_ref }}

    - name: Setup PHP and Composer
      uses: shivammathur/setup-php@2.35.5
      with:
        php-version: '8.4'
        tools: composer:v2

    - name: Install Laravel Pint
      run: composer global require laravel/pint

    - name: Run Pint
      run: pint

    - name: Push Changes Back to Repo
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'gh@cristiankozlowski.com'
        git add .
        git commit -m "Apply Laravel Pint fixes" || exit 0
        git push origin HEAD:${{ github.head_ref }}
